services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=6526
      - POSTGRES_DB=fastapitest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:6526@db:5432/fastapitest
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
